# Generated by Django 3.1.7 on 2021-05-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('employeeFirstName', models.CharField(max_length=50, verbose_name='Çalışan İsmi')),
                ('employeeLastName', models.CharField(max_length=50, verbose_name='Çalışan Soyismi')),
                ('employeeEmail', models.EmailField(max_length=120, verbose_name='Çalışan Mail Adresi')),
                ('employeePassword', models.CharField(max_length=50, verbose_name='Çalışan Parola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
