# Generated by Django 3.1.7 on 2021-05-19 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('found_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Kullanıcı Adı')),
                ('managerFirstName', models.CharField(max_length=50, verbose_name='Yönetici İsim ')),
                ('managerLastName', models.CharField(max_length=50, verbose_name='Yönetici Soyisim ')),
                ('managerEmail', models.EmailField(max_length=254, verbose_name='Yönetici Email')),
                ('managerPassword', models.CharField(max_length=25, verbose_name='Yönetici Parola')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_manager.company')),
                ('managerEmployees', models.ManyToManyField(blank=True, to='employee.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='p_manager.projectmanager')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_invites', to='p_manager.projectmanager')),
            ],
        ),
    ]
